#  application.yml
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/rooting_main?serverTimezone=Asia/Seoul
    username: jkimpro10
    password: jun48675@#
    jpa:
      hibernate:
        ddl-auto: update # 운영시에는 validate 추천
      show-sql: true
server:
  port: 8080
  servlet:
    path: /
    context-path: /

test: aaa

##LOCAL
#---
#spring:
#  profiles: local
#
#logging:
#  config: classpath:logback-${spring.profiles.active}.xml
#
#sftp:
#  url: 10.52.221.214
#  usr: service
#  key: /ucs_key/echo.private
#  phrase: smart4c
#  promptPwd: false
#  promptPhrase: true
#  promptYN: false
#  rootPath: /home/service/
#  pwd:
#
#download:
#  attach:
#    file:
#      server:
#        folder: C:/upload/